export * from './types.ts';
export * from './grid.ts';
export * from './shape.ts';
export { Rng } from './random.ts';
export { State, JOIN, WALL, UNKNOWN, regionsFromLabels, stateFromLabels } from './state.ts';
export type { Comp, EdgeValue } from './state.ts';
export { createEngine, initialState, propagate, verify } from './engine.ts';
export type { Engine, Step } from './engine.ts';
export { solve, countSolutions, isUnique } from './solver.ts';
export type { SolveOptions, SolveResult } from './solver.ts';
export { solveLogically, difficultyScore, starsFor, TIER_NAMES } from './logical.ts';
export type { LogicalResult, LogicalOptions } from './logical.ts';
export { generate, uniqueWith, sameLabels } from './generator/generate.ts';
export type { GenerateOptions, GeneratedPuzzle } from './generator/generate.ts';
export { growPartition, tilePartition, randomBank, catalogBank, randomShape, regionsOf, adjacentRegions } from './generator/partition.ts';
export { BANK_CATALOG, BANK_SIZE_WEIGHTS } from './generator/bankCatalog.ts';
export { deriveClueUnits } from './generator/clues.ts';
export { randomMask, isNice } from './generator/mask.ts';
export type { MaskOptions, Symmetry } from './generator/mask.ts';
export { render, renderLabels } from './render.ts';
